MACPortal/Controllers/ManageBrokersController.cs
using System;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using BootstrapMvcSample.Controllers;
using MACPortal.Models.Users;
using MACPortal.DAL;
using WebGrease.Css.Extensions;
using WebMatrix.WebData;

namespace MACPortal.Controllers
{
    public class ManageBrokersController : BootstrapBaseController
    {
        private PortalContext db = new PortalContext();

        //
        // GET: /ManageBrokers/

        public ActionResult Index()
        {
            var employees = db.Employees.Where(e => e is Broker).Include(b => b.User);
            return View(employees.ToList().Cast<Broker>());
        }

        //
        // GET: /ManageBrokers/Details/5

        public ActionResult Details(int id = 0)
        {
            Broker broker = (Broker)db.Employees.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }

        //
        // GET: /ManageBrokers/Create

        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserID", "UserName");
            ViewBag.ManagersDropDown = CreateManagersDropDown();
            return View();
        }

        //
        // POST: /ManageBrokers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Broker broker)
        {

            if (ModelState.IsValid)
            {
                broker.CPF = broker.CPF.Replace(".", String.Empty).Replace("-", String.Empty).Trim();
                var registerError = AccountController.RegisterEmployee(broker.CPF, broker.CPF);
                if (registerError != null)
                {   
                    ModelState.AddModelError("", registerError);
                }
                broker.UserID = WebSecurity.GetUserId(broker.CPF);
                broker.Manager = (Manager)db.Employees.Find(broker.ManagerID);
                db.Employees.Add(broker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ManagersDropDown = CreateManagersDropDown();
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserID", "UserName", broker.UserID);
            return View(broker);
        }

        //
        // GET: /ManageBrokers/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Broker broker = (Broker)db.Employees.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManagersDropDown = CreateManagersDropDown(broker);
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserID", "UserName", broker.UserID);
            return View(broker);
        }

        //
        // POST: /ManageBrokers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Broker broker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(broker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ManagersDropDown = CreateManagersDropDown(broker);
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserID", "UserName", broker.UserID);
            return View(broker);
        }

        //
        // GET: /ManageBrokers/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Broker broker = (Broker)db.Employees.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }

        //
        // POST: /ManageBrokers/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Broker broker = (Broker)db.Employees.Find(id);
            var membership = (SimpleMembershipProvider)Membership.Provider;
            var roles = (SimpleRoleProvider)Roles.Provider;
            roles.RemoveUsersFromRoles(new[] {broker.User.UserName}, new[]{"Member"});
            membership.DeleteAccount(broker.User.UserName);
            db.Employees.Remove(broker);
            var userProfile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userProfile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }



        private Collection<SelectListItem> CreateManagersDropDown(Broker broker = null)
        {
            var managersDropDown = new Collection<SelectListItem>();
            db.Employees.Where(e => e is Manager).ToList().Cast<Manager>().ForEach(m => managersDropDown.Add(new SelectListItem
            {
                Selected = broker != null && broker.ManagerID == m.UserID,
                Text = m.Name,
                Value = Convert.ToString(m.UserID)
            }));
            return managersDropDown;
        }
    }
}

MACPortal/Views/Shared/Details.cshtml
@using BootstrapSupport
@model Object
<fieldset>
    <legend>@Model.GetLabel() <small>Details</small></legend>
    <dl> <!-- use this class on the dl if you want horizontal styling http://twitter.github.com/bootstrap/base-css.html#typography  class="dl-horizontal"-->     
        @foreach(var property in Model.VisibleProperties())
        {
            <dt>
                @property.GetLabel().ToSeparatedWords()
            </dt>
            <dd>
                @Html.Display(property.Name)                
            </dd>
        }
    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", Model.GetIdValue()) |
    @Html.ActionLink("Back to List", "Index")
</p>

MACPortal/Views/Shared/_AvatarPortraitPartial.cshtml
<div id="avatar-container">
    <div id="loading">Carregando Editor</div>
    <div id="avatar" class="avatar-editor-portrait">
    </div>
</div>

MACPortal/Views/Shared/_AvatarScriptsPartial.cshtml
@using MACPortal.Extensions
@model MACPortal.ViewModel.AvatarVM

@Scripts.Render("~/bundles/jqueryval")
    @{ Html.RenderPartial("_AvatarRendererPartial"); }
    <script type="text/javascript">
        $(function () {
            avatar.Start(AvatarLoaded);
        });

        var loaded;
        function AvatarLoaded() {
            loaded = true;
            FormControlChange('hair,hair-color', $("#hair-control"));
            ColorizeForm($("#skin-color-form"));
            ColorizeForm($("#mouth-color-form"));
            ColorizeForm($("#hair-color-form"));
            ColorizeForm($("#clothes-color-form"));
            ColorizeForm($("#eyes-color-form"));

            avatar.SetHair("@Model.AvatarHair".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetFace("@Model.AvatarFace".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetEyes("@Model.AvatarEyes".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetMouth("@Model.AvatarMouth".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetNose("@Model.AvatarNose".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetEars("@Model.AvatarEars".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetClothes("@Model.AvatarClothes".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetHeadAccessory("@Model.AvatarAccessoryHead".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetBodyAccessory("@Model.AvatarAccessoryBody".match(/(\d+)(?!.*\d)/)[0] - 1);
            avatar.SetFaceAccessory("@Model.AvatarAccessoryFace".match(/(\d+)(?!.*\d)/)[0] - 1);

            avatar.SetClothesColor(parseInt("@Model.AvatarClothesColor.DisplayName().Substring(0, 6)", 16));
            avatar.SetEyesColor(parseInt("@Model.AvatarEyesColor.DisplayName().Substring(0, 6)", 16));
            avatar.SetHairColor(parseInt("@Model.AvatarHairColor.DisplayName().Substring(0, 6)", 16));
            avatar.SetMouthColor(parseInt("@Model.AvatarMouthColor.DisplayName().Substring(0, 6)", 16));
            avatar.SetSkinColor(parseInt("@Model.AvatarSkinColor.DisplayName().Substring(0, 6)", 16));
            
            AvatarChanged();
            $("#avatar-form").slideDown();
        }
        
        function ColorizeForm(form) {
            form.find(".btn").each(function () {
                var $this = $(this);
                var color = $this.text().substring(0,6);
                $this.attr("data-color", color);
                $this.attr("class", $this.attr("class") + " color-btn-container");
                var colorDiv = document.createElement('div');
                colorDiv.setAttribute("class", "color-btn");
                colorDiv.setAttribute("style", 'color:transparent; background-color: #' + color + ';');
                $this.contents().filter(function () {  //
                    return this.nodeType == 3; //Node.TEXT_NODE
                }).remove();
                $this.append(colorDiv);
            });
        }

        var currentForms;
        var currentFormsNames, currentButton;
        var first;
        function FormControlChange(formName, button) {
            if (!loaded) return;
            if (currentFormsNames == formName) return;
            var i;
            currentFormsNames = formName;
            if (currentButton != null) {
                currentButton.removeClass("active");
            }
            if (currentForms != null) {
                for (i = 0; i < currentForms.length; i++)
                {
                    currentForms[i].slideUp();
                }
            }
            
            var formsNames = currentFormsNames.split(",");
            currentButton = $(button);
            currentForms = new Array();
            for (i = 0; i < formsNames.length; i++) {
                currentForms.push($("#" + formsNames[i] + "-form"));
            }
            if (currentButton != null) {
                currentButton.addClass("active");
            }
            if (currentForms != null) {
                for (i = 0; i < currentForms.length; i++) {
                    currentForms[i].slideDown();
                }
            }
        }

        function AvatarChanged() {
            var image = avatar.GetImage();
            image = image.replace('data:image/png;base64,', '');
            $("#AvatarFileInput").val(image);
        }

        function HairChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetHair(targetIndex);
            AvatarChanged();
        }
        
        function EarsChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetEars(targetIndex);
            AvatarChanged();
        }
        
        function MouthChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetMouth(targetIndex);
            AvatarChanged();
        }
        
        function ClothesChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetClothes(targetIndex);
            AvatarChanged();
        }
        
        function NoseChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetNose(targetIndex);
            AvatarChanged();
        }
        
        function EyesChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetEyes(targetIndex);
            AvatarChanged();
        }
        
        function AccHeadChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetHeadAccessory(targetIndex);
            AvatarChanged();
        }
        
        function AccBodyChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetBodyAccessory(targetIndex);
            AvatarChanged();
        }
        
        function AccFaceChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetFaceAccessory(targetIndex);
            AvatarChanged();
        }
        
        function FaceChange(context) {
            var targetIndex = context.value.match(/(\d+)(?!.*\d)/)[0] - 1;
            avatar.SetFace(targetIndex);
            AvatarChanged();
        }
        
        function SkinColorChange(context) {
            var targetIndex = $(context).parent().attr("data-color");
            avatar.SetSkinColor(parseInt(targetIndex, 16));
            AvatarChanged();
        }
        
        function HairColorChange(context) {
            var targetIndex = $(context).parent().attr("data-color");
            avatar.SetHairColor(parseInt(targetIndex, 16));
            AvatarChanged();
        }
        
        function ClothesColorChange(context) {
            var targetIndex = $(context).parent().attr("data-color");
            avatar.SetClothesColor(parseInt(targetIndex, 16));
            AvatarChanged();
        }
        
        function EyesColorChange(context) {
            var targetIndex = $(context).parent().attr("data-color");
            avatar.SetEyesColor(parseInt(targetIndex, 16));
            AvatarChanged();
        }

        function MouthColorChange(context) {
            var targetIndex = $(context).parent().attr("data-color");
            avatar.SetMouthColor(parseInt(targetIndex, 16));
            AvatarChanged();
        }
    </script>

MACPortal/Views/Shared/_BootstrapLayout.empty.cshtml
@using System.Web.Optimization
@using BootstrapSupport
@using NavigationRoutes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Styles.Url("~/content/css")" rel="stylesheet"/>
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>    <link href="@Styles.Url("~/Content/css-responsive")" rel="stylesheet" type="text/css" />
    @RenderSection("head", required: false)
    @Html.Partial("_html5shiv")
    @* favicons and touch icons go here *@
</head>
<body>
    <div class="container">

        @Html.Partial("_alerts")
        @RenderBody()
        <hr>
        <footer>
            <p>&copy; Company @System.DateTime.Now.ToString("yyyy")</p>
        </footer>

    </div> <!-- container -->
    @Scripts.Render("~/js")
    @RenderSection("Scripts", required: false)
</body>
</html>

MACPortal/Views/Shared/_ContactPartial.cshtml
@model MACPortal.ViewModel.ContactVM

@using (var f = Html.Bootstrap().Begin(new Form().Type(FormType.Horizontal).InputWidthMd(9)))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @f.FormGroup().TextBoxFor(m => m.Name).Disabled(Model.Name != null).Label().WidthMd(3)
    @f.FormGroup().TextBoxFor(m => m.CPF).Disabled(Model.CPF != null).Label().WidthMd(3)
    @f.FormGroup().TextBoxFor(m => m.Email).Disabled(Model.Email != null).Label().WidthMd(3)
    @f.FormGroup().TextBoxFor(m => m.Title).Label().WidthMd(3)
    @f.FormGroup().TextAreaFor(m => m.Message).Rows(10).Label().WidthMd(3)
    
    @Html.Bootstrap().SubmitButton().AppendIcon("glyphicon glyphicon-chevron-right").Text("Enviar").Size(ButtonSize.Large).ButtonBlock()

}

MACPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Portal Campanha de Incentivo MAC @if (ViewBag.Section != null)
                                                                 {
                                                                    <text> | @ViewBag.Section</text>
                                                                 }</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                @RenderSection("header", required:true)
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: true)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; Copyright @DateTime.Now.Year - MAC Construtora e Incorporadora - Todos os direitos reservados</p>
                </div>
                
                <div>
                    @RenderSection("navigation", required:false)
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: true)
    </body>
</html>

MACPortal/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Section = "Administrator";
    //Layout = "~/Views/Shared/_Layout.cshtml"; 
    Layout = "~/Views/Shared/_BootstrapLayout.basic.cshtml";
}

@section header
{
    <div>
        <p class="site-title">@Html.ActionLink("Portal Campanha de Incentivo MAC", "Index", "Admin")</p>
    </div>
}

@section navigation
{
    @using (var nav = Html.Bootstrap().Begin(new Nav().Style(NavType.Pills)))
    {
        @nav.ActionLink("Corretores", "Index", "ManageBrokers")
        @nav.ActionLink("Gerentes", "Index", "ManageManager")
        @nav.ActionLink("Coordenadores", "Index", "ManageCoordinator")
        @nav.ActionLink("Vendas", "Index", "ManageSales")
        @nav.ActionLink("Recompensas", "Index", "ManageReward")
    }
}


@RenderBody()
@section scripts { @RenderSection("scripts", required:false) }
@section featured { @RenderSection("featured", required:false) }

MACPortal/Views/Shared/_LayoutLogout.cshtml
@{
    //Layout = "~/Views/Shared/_Layout.cshtml"; 
    ViewBag.InverseNavigation = true;
    Layout = "~/Views/Shared/_BootstrapLayout.basic.cshtml";
}

@section header
{
}

@section navigation
{
    @using (var nav = Html.Bootstrap().Begin(new Nav().Style(NavType.Pills).SetLinksActiveByControllerAndAction()))
    {
        @nav.ActionLink("Login", "Login", "Account")
        @nav.ActionLink("Esqueci Minha Senha", "ForgotPassword", "Account")
        @nav.ActionLink("Fale Conosco", "Contact", "Account")
    }
}

@RenderBody()
@section scripts { @RenderSection("scripts", required:false) }
@section featured { @RenderSection("featured", required:false) }

MACPortal/Views/Shared/_LayoutMember.cshtml
@model MACPortal.ViewModel.BaseMemberVM

@{
    ViewBag.Section = "Membro";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_BootstrapLayout.basic.cshtml";
}

@section header
{
    <div class="image-glow">
        <p>@Html.ActionLink("Portal Campanha de Incentivo MAC", "Index", "Member", null, new {@class = "portal-logo portal-logo-small"})</p>
    </div>
}

@section navigation
{
    @using (var nav = Html.Bootstrap().Begin(new Nav().Style(NavType.Pills).SetLinksActiveByControllerAndAction()))
    {
        @nav.ActionLink("Home", "Index", "Member")
        @nav.ActionLink("Ranking", "Ranking", "Member")
        @nav.ActionLink("Premiação", "Rewards", "Member")
        @nav.ActionLink("Regulamento", "Regulation", "Member")
        @nav.ActionLink("Fale Conosco", "Contact", "Member")
    }
}

<div class="user-info">
    <div class="user-info-block user-info-header">Meu Perfil</div>
    <div class="user-info-block">
        <ul>
            <li class="avatar-portrait" style="background-image: url(@Model.Employee.AvatarUrl)"></li>
            <li>
                @Model.Employee.ComercialName
            </li>
        </ul>
    </div>

    <div class="user-info-block">
        <ul>
            <li>
                @Html.Bootstrap().ActionLinkButton("Minha Pontuação", "Points")
            </li>
            <li>
                @Html.Bootstrap().ActionLinkButton("Editar Perfil", "EditProfile")
            </li>
            <li>
                @Html.Bootstrap().ActionLinkButton("Editar Avatar", "EditAvatar")
            </li>
            <li>
                @Html.Bootstrap().ActionLinkButton("Mudar Senha", "ChangePassword")
            </li>
        </ul>
    </div>
    
    <div class="user-info-block">
        <ul>
            <li class="stats-block">
                <b>@(Model.Employee.Ranking)º</b>Colocação
            </li>
            <li class="stats-block">
                <b>@Model.Employee.Points</b>Total de Pontos
            </li>
            <li class="stats-block">
                <b>@Model.Employee.Sales</b>Total de Vendas
            </li>
        </ul>
    </div>
    <div class="user-info-block">
        <ul>
            <li>
                @Html.Bootstrap().ActionLinkButton("Sair Desta Conta", "LogOff", "Account")
            </li>
        </ul>
    </div>
</div>
<div class="member-content">
    @RenderBody()
</div>
            

@section scripts { @RenderSection("scripts", required:false) }
@section featured { @RenderSection("featured", required:false) }

MACPortal/Views/Shared/_RankingTablePartial.cshtml
@model MACPortal.ViewModel.RankingVM

@using (Html.Bootstrap().Begin(new Table().Striped().Class("ranking-table")))
{
    var rankingsList = Model.Rankings;
    for (int i = 0; i < rankingsList.Count; i++)
    {
        var ranking = rankingsList[i];
        
        <tr class="ranking-info-block @{
                                          if (ranking.CurrentUser)
                                          {
                                            <text> ranking-info-selected </text>
                                          }
                                      }">
            <td class="ranking-portrait-small">
                <p class="avatar-portrait" style="background-image: url(@ranking.AvatarUrl?width=75)"></p>
            </td>
            <td class="ranking-number">@(i + 1)º</td>
            <td class="ranking-name">@ranking.Name</td>
            <td class="ranking-points">@ranking.Points</td>
        </tr>
    }
}

MACPortal/Views/Shared/_alerts.cshtml
@using BootstrapSupport
@if (TempData.ContainsKey(Alerts.ATTENTION))
{
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Attention!</h4>
        @TempData[Alerts.ATTENTION]
    </div>
}
@foreach(string key in Alerts.ALL.Except(new[] {Alerts.ATTENTION}))
    {
        if (TempData.ContainsKey(key))
         {
             <div class="alert alert-@key">
                 <button type="button" class="close" data-dismiss="alert">x</button>
                 @TempData[key]
             </div>
         }
    }

MACPortal/Views/Shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5shiv.js"></script>
    <![endif]-->